version: "3.7"

services:
  qatime:
    build: .
    ports:
      # Forwarding for the Qumulo REST API port
      - "8000:8000"

  redis:
    image: redis

  rsyslog:
    build: rsyslog
    ports:
      - "514:514"
      - "514:514/udp"
